<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="3">

  <testsuite name="test"
    errors="0" failures="1" hostname="" id="" package="test" skipped="0"
    tests="3" time="7.837" timestamp="">
  
    <testcase name="Open Website Vente privÃ©e" classname="test" time="0.1980" assertions="1">

    
    </testcase>
  
    <testcase name="Check block login" classname="test" time="0.4740" assertions="4">

    

    

    

    
    </testcase>
  
    <testcase name="Open Registration page" classname="test" time="7.165" assertions="2">

      <failure message="Testing if the URL is [0;33m&#39;https://www.veepaee.fr/registration/registration?CountryCodeUser=FR&amp;accessButtonText=Inscrivez-vous%20maintenant%20!&#39;[0m in 5000ms - expected [0;32m&#34;is &#39;https://www.veepaee.fr/registration/registration?CountryCodeUser=FR&amp;accessButtonText=Inscrivez-vous%20maintenant%20!&#39;&#34;[0m but got: [0;31m&#34;https://www.veepee.fr/registration/registration?CountryCodeUser=FR&amp;accessButtonText=Inscrivez-vous%20maintenant%20!&#34;[0m [0;90m(5244ms)[0m">    at DescribeInstance.&lt;anonymous&gt; (/home/rativeau/nightTest/tests/test.js:41:17)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)</failure>

    <failure message="    at DescribeInstance.&lt;anonymous&gt; (/home/rativeau/nightTest/tests/test.js:41:17)">    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)</failure>
    </testcase>
  

  

  
  </testsuite>
</testsuites>
